# Generated by Django 2.2.2 on 2019-06-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190609_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundemail',
            name='message_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
