# Generated by Django 2.2.2 on 2019-06-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inboundemail_message_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundemail',
            name='message_url',
        ),
    ]
