# Generated by Django 2.2.2 on 2019-06-08 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shoppers',
            field=models.ManyToManyField(related_name='_order_shoppers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
