# Generated by Django 2.2.2 on 2019-06-09 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inboundemail'),
        ('orders', '0002_order_shoppers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.InboundEmail'),
        ),
    ]
