# Generated by Django 2.2.2 on 2019-06-09 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='origin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.InboundEmail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shoppers',
            field=models.ManyToManyField(blank=True, related_name='_order_shoppers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
