# Generated by Django 2.2.2 on 2019-06-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190609_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shares',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
